services:
  nestjs_starter_test_postgres: # needs updating
    image: postgres:latest
    container_name: nestjs_starter_test_postgres # needs updating
    restart: 'no'
    env_file:
      - .env.test
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5444:5432"
    volumes:
      - nestjs_starter_test_postgres_data:/var/lib/postgresql # needs updating
    networks:
      - nestjs_starter_test_network
  nestjs_starter_test_redis:
    image: redis:latest
    container_name: nestjs_starter_test_redis
    ports:
      - "6380:6379"
    volumes:
      - nestjs_starter_test_redis_data:/data
    networks:
      - nestjs_starter_test_network

networks:
  nestjs_starter_test_network: # needs updating
    driver: bridge

volumes:
  nestjs_starter_test_postgres_data: # needs updating
    driver: local
  nestjs_starter_test_redis_data: # needs updating
    driver: local